# This is a basic workflow to help you get started with Actions

name: My First Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "01_DockerTest" ]
  pull_request:
    branches: [ "01_DockerTest" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 01_DockerTest branch
        uses: actions/checkout@v4
        with:
          ref: 01_DockerTest


      - name: Build Docker image
        run: docker build -t hello-world-nginx:v1 .

      - name: Run Docker container
        run: docker run -d -p 8080:80 hello-world-nginx:v1

      - name: Show running containers
        run: docker ps

