name: Kubectl Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy-to-k8s:
    runs-on: self-hosted  # your local runner, Linux or Windows

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate random pod name
        id: vars
        shell: powershell
        run: |
          $random = Get-Random -Minimum 10000 -Maximum 99999
          echo "podname=mypod-$random" >> $env:GITHUB_OUTPUT
    

      - name: Replace placeholder in pod-template.yaml
        shell: powershell
        run: |
          $podname = '${{ steps.vars.outputs.podname }}'
          (Get-Content pod-template.yaml) -replace 'mypod-PLACEHOLDER', $podname | Set-Content generated-pod.yaml
          Get-Content generated-pod.yaml

      - name: Apply Pod to Kubernetes cluster
        run: |
          kubectl apply -f generated-pod.yaml

      - name: Get pods in namespace
        run: |
          kubectl get pods -n default
